issue-3
checkly/checkly-k8s pull request #4
Opened 2024-01-26 20:00 UTC by gespi1

2024-01-28 20:09 UTC, tnolet commented
@gespi1 awesome thanks. I will ask @benben to have a look at this as my k8s and helm knowledge is rusty.

2024-01-30 08:34 UTC, benben requested changes
Hey @gespi1!

Thank you so much for contributing! This is a great addition!

I left two comments. Can you please add a tiny section to the README about this new functionality?

Thanks again.

2024-01-30 08:34 UTC, benben commented on helm-chart/templates/validate.yaml
> +{{- end }}
```suggestion
```

this is the same as line 13

2024-01-30 08:34 UTC, benben commented on helm-chart/values.yaml
> +  apiKey: replace_me
let's make this variable empty or remove it, otherwise you run into weird setups where you have to explictly do a 

```
  apiKey:
```
to set it to nothing, otherwise you always get the default value.

2024-01-30 16:01 UTC, gespi1 commented on helm-chart/templates/validate.yaml
> +{{- end }}
removed dupe

2024-01-30 16:17 UTC, gespi1 commented
@benben ty for taking the time to review this, appreciate it :) . Updated the PR. Let me know what you think

2024-01-30 19:40 UTC, benben approved these changes
beautiful. thank you so much!

2024-01-30 19:41 UTC, merged